# Generated by Django 4.1.2 on 2023-01-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stuff',
            new_name='stuff1',
        ),
    ]
