# Generated by Django 4.1.2 on 2023-01-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_stuff_stuff1'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
    ]
