# Generated by Django 4.1.2 on 2023-01-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stuff1',
            name='collectioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
