# Generated by Django 4.1.2 on 2023-01-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_stuff1_collectioner_collection_collectioner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collectioner',
        ),
        migrations.AddField(
            model_name='stuff1',
            name='collectioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.collection'),
        ),
    ]
