# Generated by Django 4.1.2 on 2023-01-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_collection_collectioner_stuff1_collectioner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff1',
            old_name='collectioner',
            new_name='collector',
        ),
    ]
