# Generated by Django 4.1.2 on 2023-01-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_collectioner_stuff1_collector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff1',
            name='collector',
        ),
        migrations.AddField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.stuff1'),
        ),
    ]
