# Generated by Django 4.1.2 on 2023-01-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_stuff1_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff1',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='app.collection'),
        ),
    ]
