# Generated by Django 4.1.2 on 2023-01-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_stuff1_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
