# Generated by Django 4.1.2 on 2023-01-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_collection_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='num',
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
