# Generated by Django 4.1.2 on 2023-02-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_collection_id_alter_stuff1_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
