# Generated by Django 4.1.2 on 2023-02-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_collection_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stuff1',
            new_name='Books',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rate', models.IntegerField()),
                ('description', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.books')),
            ],
        ),
    ]
