# Generated by Django 4.1.2 on 2023-02-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_stuff1_books_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.review'),
        ),
    ]
