# Generated by Django 4.1.2 on 2023-02-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_books_description_alter_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='review_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Number', to='app.books'),
        ),
        migrations.AddField(
            model_name='review',
            name='titleReview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titleReview', to='app.books'),
            preserve_default=False,
        ),
    ]
