# Generated by Django 4.1.2 on 2023-02-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_review_description_books_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(default='Awesome'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='app.review'),
        ),
    ]
