# Generated by Django 4.1.2 on 2023-02-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_books_description_alter_review_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='book_t',
            new_name='Books',
        ),
        migrations.RemoveField(
            model_name='books',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_num',
        ),
        migrations.AddField(
            model_name='books',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.collection'),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='books',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='Books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.books'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(),
        ),
    ]
