# Generated by Django 4.1.2 on 2023-02-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Books',
            new_name='Books_review',
        ),
    ]
