# Generated by Django 4.1.2 on 2023-02-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_books_review_books_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Books',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='books',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.books'),
        ),
    ]
